waline:
  enable: true # 是否启用
  serverURL: "" # waline 服务端地址
  lang: "zh-CN" # 评论界面语言
  locale: {} # 本地化替换，详见 waline 文档
  emoji: # 表情包，默认为 waline 官方配置
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # 评论可以填写的项目
    - nick
    - mail
    - link
  requiredMeta: # 评论必须填写的项目
    - nick
    - mail
  wordLimit: 0 # 评论字数上限 (不建议为 0)
  pageSize: 10 # 每页显示评论条数
  pageview: true # 页面浏览量显示

# 本文作者： Ruri Shimotsuki @優萌初華
# 本文链接： https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/config/
# 版权声明： 本站所有文章除特别声明外，均采用 (CC)BY-NC-SA 许可协议。转载请注明出处！

sidebar:
  # Sidebar Position.
  position: left
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.png

widgets:
  random_posts: true # 显示随机文章
  recent_comments: true # 显示最近评论

# 页尾全站统计
footer:
  since: 2010
  count: true

# 文章界面统计
post:
  count: true

